-- =====================================================================
-- E-PAY FINTECH - SCRIPT DE BANCO DE DADOS ORACLE SQL
-- Autor: Douglas Cristian Ferreira
-- Descrição: Tabelas e sequências para o Internet Banking E-Pay
-- =====================================================================

-- 1. LIMPEZA PRÉVIA (caso precise recriar as tabelas)
BEGIN
    FOR t IN (SELECT table_name FROM user_tables WHERE table_name LIKE 'TB_EPAY_%') LOOP
        EXECUTE IMMEDIATE 'DROP TABLE ' || t.table_name || ' CASCADE CONSTRAINTS';
    END LOOP;
    FOR s IN (SELECT sequence_name FROM user_sequences WHERE sequence_name LIKE 'SQ_EPAY_%') LOOP
        EXECUTE IMMEDIATE 'DROP SEQUENCE ' || s.sequence_name;
    END LOOP;
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

-- 2. SEQUÊNCIAS PARA GERAÇÃO AUTOMÁTICA DE IDs
CREATE SEQUENCE SQ_EPAY_USUARIO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SQ_EPAY_CONTA START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SQ_EPAY_TRANSACAO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SQ_EPAY_CARTAO START WITH 1 INCREMENT BY 1 NOCACHE;

-- 3. TABELA DE USUÁRIOS (CLIENTES DA FINTECH)
CREATE TABLE TB_EPAY_USUARIO (
    ID_USUARIO       NUMBER(10) NOT NULL,
    NOME             VARCHAR2(120) NOT NULL,
    EMAIL            VARCHAR2(100) NOT NULL,
    SENHA_HASH       VARCHAR2(255) NOT NULL,
    CPF              VARCHAR2(14) NOT NULL,
    TELEFONE         VARCHAR2(20),
    DATA_CADASTRO    TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_EPAY_USUARIO PRIMARY KEY (ID_USUARIO),
    CONSTRAINT UK_EPAY_USUARIO_EMAIL UNIQUE (EMAIL),
    CONSTRAINT UK_EPAY_USUARIO_CPF UNIQUE (CPF)
);

-- 4. TABELA DE CONTAS CORRENTES / CARTEIRAS
CREATE TABLE TB_EPAY_CONTA (
    ID_CONTA         NUMBER(10) NOT NULL,
    ID_USUARIO       NUMBER(10) NOT NULL,
    NUMERO_CONTA     VARCHAR2(10) NOT NULL,
    AGENCIA          VARCHAR2(6) DEFAULT '0001' NOT NULL,
    SALDO            NUMBER(15,2) DEFAULT 0.00 NOT NULL,
    CHAVE_PIX        VARCHAR2(100),
    STATUS           VARCHAR2(20) DEFAULT 'ATIVA' NOT NULL,
    DATA_ABERTURA    TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_EPAY_CONTA PRIMARY KEY (ID_CONTA),
    CONSTRAINT FK_EPAY_CONTA_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES TB_EPAY_USUARIO(ID_USUARIO),
    CONSTRAINT UK_EPAY_CONTA_NUMERO UNIQUE (NUMERO_CONTA),
    CONSTRAINT UK_EPAY_CONTA_PIX UNIQUE (CHAVE_PIX),
    CONSTRAINT CK_EPAY_CONTA_STATUS CHECK (STATUS IN ('ATIVA', 'BLOQUEADA', 'ENCERRADA')),
    CONSTRAINT CK_EPAY_CONTA_SALDO CHECK (SALDO >= 0) -- Evita saldo negativo sem cheque especial
);

-- 5. TABELA DE TRANSAÇÕES FINANCEIRAS (EXTRATO / PIX / TRANSFERÊNCIAS)
CREATE TABLE TB_EPAY_TRANSACAO (
    ID_TRANSACAO     NUMBER(10) NOT NULL,
    ID_CONTA_ORIGEM  NUMBER(10),
    ID_CONTA_DESTINO NUMBER(10) NOT NULL,
    TIPO             VARCHAR2(30) NOT NULL,
    VALOR            NUMBER(15,2) NOT NULL,
    DATA_HORA        TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DESCRICAO        VARCHAR2(255),
    CONSTRAINT PK_EPAY_TRANSACAO PRIMARY KEY (ID_TRANSACAO),
    CONSTRAINT FK_EPAY_TRANS_ORIGEM FOREIGN KEY (ID_CONTA_ORIGEM) REFERENCES TB_EPAY_CONTA(ID_CONTA),
    CONSTRAINT FK_EPAY_TRANS_DESTINO FOREIGN KEY (ID_CONTA_DESTINO) REFERENCES TB_EPAY_CONTA(ID_CONTA),
    CONSTRAINT CK_EPAY_TRANS_VALOR CHECK (VALOR > 0),
    CONSTRAINT CK_EPAY_TRANS_TIPO CHECK (TIPO IN ('PIX', 'TRANSFERENCIA', 'DEPOSITO', 'PAGAMENTO', 'RENDIMENTO'))
);

-- 6. TABELA DE CARTÕES (CRÉDITO / DÉBITO / VIRTUAL)
CREATE TABLE TB_EPAY_CARTAO (
    ID_CARTAO        NUMBER(10) NOT NULL,
    ID_CONTA         NUMBER(10) NOT NULL,
    NUMERO_MASCARADO VARCHAR2(19) NOT NULL,
    NOME_TITULAR     VARCHAR2(120) NOT NULL,
    VALIDADE         VARCHAR2(7) NOT NULL,
    CVV              VARCHAR2(4) NOT NULL,
    TIPO             VARCHAR2(20) DEFAULT 'VIRTUAL' NOT NULL,
    LIMITE_TOTAL     NUMBER(15,2) DEFAULT 5000.00 NOT NULL,
    LIMITE_UTILIZADO NUMBER(15,2) DEFAULT 0.00 NOT NULL,
    STATUS           VARCHAR2(20) DEFAULT 'ATIVO' NOT NULL,
    CONSTRAINT PK_EPAY_CARTAO PRIMARY KEY (ID_CARTAO),
    CONSTRAINT FK_EPAY_CARTAO_CONTA FOREIGN KEY (ID_CONTA) REFERENCES TB_EPAY_CONTA(ID_CONTA),
    CONSTRAINT CK_EPAY_CARTAO_STATUS CHECK (STATUS IN ('ATIVO', 'BLOQUEADO', 'CANCELADO')),
    CONSTRAINT CK_EPAY_CARTAO_TIPO CHECK (TIPO IN ('CREDITO', 'DEBITO', 'VIRTUAL'))
);

-- 7. DADOS INICIAIS DE DEMONSTRAÇÃO (SEED DATA)
-- Senha criptografada: '123456' em BCrypt ($2a$10$w09u7uRjT4wXWqR.1/K9eeXUf.j6m5x8jG1Y8h8qgN9.80k3x4.w6)
INSERT INTO TB_EPAY_USUARIO (ID_USUARIO, NOME, EMAIL, SENHA_HASH, CPF, TELEFONE)
VALUES (SQ_EPAY_USUARIO.NEXTVAL, 'Douglas Cristian', 'douglas@epay.com.br', '$2a$10$N.ZMDJvWEx3vG3v2a8Q6se6UqM0YV6kHqNq7d1w2x8jG1Y8h8qgN9', '123.456.789-00', '(11) 98765-4321');

INSERT INTO TB_EPAY_CONTA (ID_CONTA, ID_USUARIO, NUMERO_CONTA, AGENCIA, SALDO, CHAVE_PIX)
VALUES (SQ_EPAY_CONTA.NEXTVAL, 1, '10001-9', '0001', 5420.50, 'douglas@epay.com.br');

INSERT INTO TB_EPAY_CARTAO (ID_CARTAO, ID_CONTA, NUMERO_MASCARADO, NOME_TITULAR, VALIDADE, CVV, TIPO, LIMITE_TOTAL, LIMITE_UTILIZADO, STATUS)
VALUES (SQ_EPAY_CARTAO.NEXTVAL, 1, '5520 •••• •••• 8492', 'DOUGLAS C FERREIRA', '08/31', '382', 'VIRTUAL', 8000.00, 1250.30, 'ATIVO');

INSERT INTO TB_EPAY_TRANSACAO (ID_TRANSACAO, ID_CONTA_ORIGEM, ID_CONTA_DESTINO, TIPO, VALOR, DESCRICAO)
VALUES (SQ_EPAY_TRANSACAO.NEXTVAL, NULL, 1, 'DEPOSITO', 6000.00, 'Depósito inicial de abertura de conta');

INSERT INTO TB_EPAY_TRANSACAO (ID_TRANSACAO, ID_CONTA_ORIGEM, ID_CONTA_DESTINO, TIPO, VALOR, DESCRICAO)
VALUES (SQ_EPAY_TRANSACAO.NEXTVAL, 1, 1, 'PIX', 579.50, 'Pagamento Mercado Livre');

COMMIT;
