# =====================================================================
# PERFIL ORACLE (CONEXÃO COM A BASE ACADÊMICA DA FIAP)
# Para ativar este perfil: defina spring.profiles.active=oracle no application.properties
# =====================================================================

spring.datasource.url=jdbc:oracle:thin:@oracle.fiap.com.br:1521:ORCL
spring.datasource.driverClassName=oracle.jdbc.OracleDriver
spring.datasource.username=${FIAP_ORACLE_USER:RM566847}
spring.datasource.password=${FIAP_ORACLE_PASSWORD:120598}

# Configurações do Hibernate para Oracle
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
